---
- name: Nginx  installation for Debian-based os
  package:
    name: nginx
    state: latest

- name: Nginx. Enable and start service
  service:
    name: nginx
    state: started
    enabled: yes


