---
yum_http_packages:
  - httpd

apt_http_packages:
  - apache2

default_home: "/var/www/html/"  

site_cent01: "local_cent01.site"
site_cent02: "local_cent02.site"
site_ub01: "local_ub01.site"

virtual_hosts:
  - { name: "{{ site_cent01 }}", ip: "{{ hostvars[\"cent_01\"].ansible_host }}"}
  - { name: "{{ site_cent02 }}", ip: "{{ hostvars[\"cent_02\"].ansible_host }}"}
  - { name: "{{ site_ub01 }}", ip: "{{ hostvars[\"ub_01\"].ansible_host }}"}
