---
- hosts: allhosts
  become: yes
  tasks:
  - name: Creating user {{ new_user }}
    user:
      name: "{{ new_user }}"
      shell: /bin/bash
      comment: "Managed by ansible"
      state: present
  - name: Set authorized key for user ubuntu copying it from current user
    authorized_key:
        user: "{{ new_user }}"
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
  - name: Add {{ new_user }} with nopasswd
    copy:
     dest: "/etc/sudoers.d/{{ new_user }}"
     content: "{{ new_user }} ALL=(ALL) NOPASSWD:ALL"
    tags:
      - nopasswd

