---
- name: update repository cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Redmine. Intsall depends
  apt:
    name: "{{ apt_redmine_packages }}"
    state: latest

- name: MySQL. Install and setup
  block:
  - template:
      src: templates/my.cnf.j2
      dest: ~/.my.cnf
      owner: root
      mode: 0600
  - service:
      name: mysql
      state: started
      enabled: yes

# - name: Set root user password
#   mysql_user:
#     name: root
#     host: {{ app_db_host }}
#     password: {{ app_db_password }}
#     login_user: {{ app_db_username }}
#     check_implicit_admin: true
#     login_password: ""
#     state: present

- mysql_db:
    name: "{{ app_db_name }}"
    encoding: utf8

- mysql_user:
    name: "{{ app_db_username }}"
    password: "{{ app_db_password }}"
    priv: "{{ app_db_name }}.*:ALL"

- name: Redmine. Clone repository
  git: 
    repo: "{{ app_repo }}" 
    dest: "{{ app_home }}" 
    version: '{{ app_version }}' 
    accept_hostkey: yes

- name: Redmine. Change permissions
  file:
    path: "{{ app_home }}/public"
    owner: www-data
    group: www-data
    recurse: yes

- name: Redmine. Change permissions
  file:
    path: "{{ app_home }}/tmp"
    mode: 777
    recurse: yes

- name: Config database
  template: 
    src: database.yml.j2 
    dest: "{{ app_home }}/config/database.yml"

- name: Redmine. Setup 01
  shell: |
    gem install bundler
    bundle update   
  args:
    executable: /bin/bash
    chdir: "{{ app_home }}"
  tags: 
    - setup

- name: Session store secret generation
  shell: rake generate_secret_token
  args:
   chdir: "{{ app_home }}"
   creates: "{{ app_home }}/config/initializers/secret_token.rb"
  tags:
    - setup

- name: Redmine. Setup 02
  shell: | 
    bundle exec rake db:migrate RAILS_ENV=production 
    bundle exec rake redmine:plugins:migrate RAILS_ENV=production
    bundle install --without development test
    RAILS_ENV=production rake db:migrate
    #RAILS_ENV=production REDMINE_LANG="{{ app_lang }}" rake redmine:load_default_data
    #bundle exec rails server webrick -e production
  args:
    chdir: "{{ app_home }}"
  tags:
    - setup

- name: Configuration files for virtualhost
  template:
    src: redmine.site.conf.j2
    dest: "/etc/apache2/sites-enabled/redmine.site.conf"

- name: apache_restart
  service:
    name: apache2
    state: restarted
    enabled: yes
