version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
     - ./nginx:/usr/share/nginx/html
    ports:
    - 5777:80
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Minsk
      - UMASK_SET=022
    ports:
      - 5888:8989
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Minsk
      - UMASK_SET=022
    ports:
      - 5999:7878
    restart: unless-stopped