---
- hosts: "{{ group }}"
  #gather_facts: false
  vars: 
    var_01: "Hi"
    var_02: true
    var_03: 42
    array:
      - first
      - second
    dic:
      - {name: some, test: test }
      - {name: some1, test: test1 }
  tasks:
    - name: Print host vars
      debug:
        msg: "{{ hostvars[inventory_hostname].ansible_host }},{{ ansible_user }}"
      tags:
        - inv::check
        - all_print 
    - name: Print vars
      debug:
        msg: "Var01 is: {{ var_01 }}, dic[0] is: {{ item.name }}" 
      tags:
        - vars_print
      loop: "{{ dic }}"
    - name: Print all inventory
      debug:
        msg: "{{ hostvars[inventory_hostname] }}"
      tags:
        - inventory
    - name: Print facts
      debug:
        msg: "{{ ansible_distribution }} | {{ ansible_distribution_version }}"
      tags:
        - facts


