---
- hosts: webservers
  tasks:
  - name: Print OS/version
    debug:
      msg: "{{ ansible_distribution }} | {{ ansible_distribution_version }}"
    tags:
      - os-version
  - name: Print mount point/capacity/used
    debug:
      msg: "{{ ansible_mounts }}"
    tags:
      - mount
  - name: Print RAM/capacity/free
    debug:
      msg: "{{ ansible_memory_mb }}"
    tags:
      - memory
