---
#- name: Apache2. Remove packages
#  apt:
#    name: "{{ apt_http_packages }}"
#    state: absent

- name: Apache2. Install packages
  apt:
    name: "{{ apt_http_packages }}"
    state: present
- name: Apache2. Enable and start servce
  service:
    name: apache2
    state: started
    enabled: yes
