---
- name: Test
  with_items:
  - { os: 'centos', site: 'alfa' }
  - { os: 'centos', site: 'beta' }
  - { os: 'ubuntu', site: 'alfa' }
  - { os: 'ubuntu', site: 'beta' }
  become: false
  delegate_to: 127.0.0.1
  uri:
    url: "http://{{ item.os }}.{{ item.site }}.local/"
    status_code: 200
    return_content: yes
  register: this
  failed_when: item.site not in this.content.lower()
